services:

  # Spring Boot API
  api:
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: 
